LANGUAGE = python
SCRIPT = layla.py
SAM_CMD = "C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd"
LAYLA_DIR = .layla
LAYER_NAME = hello_world
CONTENTS = pandas pyjanitor
STACK_NAME = layla-stack
S3_BUCKET = layla-bucket
AWS_REGION = eu-central-1